AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-layers-with-sam
Parameters:
  EnvironmentType:
    Type: String
    Default: 'Development'
Resources:
  NestLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: NestLayer
      Description: Nest dependencies
      ContentUri: 'layers/nest-layer/'
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: nodejs18.x
  MainAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: API
      StageName: !Ref EnvironmentType
      DefaultRouteSettings:
        DetailedMetricsEnabled: true
        ThrottlingBurstLimit: 5
        ThrottlingRateLimit: 5
      CorsConfiguration:
        AllowMethods:
          - GET
          - OPTIONS
          - POST
          - PUT
          - HEAD
          - PATCH
          - DELETE
        AllowHeaders:
          - "*"
        AllowOrigins:
          - "*"
      FailOnWarnings: true
  HelloLambdaSimple:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/hello-lambda/src
      Handler: app.handler
      Layers:
        - !Ref NestLayer
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /simple
            Method: get
            ApiId:
              Ref: MainAPI
      Runtime: nodejs18.x
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
        External:
          - "/opt/nodejs/node_modules"
  HelloLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/hello-lambda/src
      Handler: serverless.handler2
      Layers:
        - !Ref NestLayer
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /nest
            Method: get
            ApiId:
              Ref: MainAPI
      Runtime: nodejs18.x
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
        External:
          - "/opt/nodejs/node_modules"
